name: SpigotPing
main: fr.rateek.spigotping.Main
version: 1.0
author: Rateek
description: "Look your ping in Spigot & Bukkit server."
commands:
 ping:
  description: "Look your ping in Spigot & Bukkit server."